language: objective-c
osx_image: xcode9.2
branches:
only:
- master
env:
global:
- WORKSPACE=TapNetworkManager.xcworkspace
- IOS_FRAMEWORK_SCHEME="TapNetworkManager_Carthage"
matrix:
- DESTINATION="OS=8.0,name=iPhone 8"          SCHEME="$IOS_FRAMEWORK_SCHEME"
before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
